const { h1, h2, p, bullet, numbered } = require('./helpers');

function buildPart5() {
  return [
    h1('Diskusija', true, '5'),

    h2('5.1. Doprinos StatsBomb 360 prostornih podataka'),
    p('Centralni nalaz rada je da Model B konzistentno i u svim primenjenim validacionim šemama nadmašuje Model A, i u pogledu diskriminacije i u pogledu kalibracije. Doprinos nije dramatičan u apsolutnom iznosu (na primer, oko 0,02 razlike u ROC AUC), ali je dosledan kroz sve kombinacije algoritma i validacione šeme, što povećava pouzdanost zaključka da je reč o stvarnom, ne slučajnom efektu. Konkretnija i možda informativnija potvrda dolazi iz SHAP analize, gde se otvorenost ugla ka golu, atribut koji ne postoji bez StatsBomb 360 podataka, plasira kao drugi najuticajniji atribut u celom modelu.'),
    p('Ovaj nalaz je u skladu sa postojećom literaturom o doprinosu prostornih podataka xG modelima, uključujući i sopstvenu praksu kompanije StatsBomb. Rad ne tvrdi da je po prvi put otkrio da prostorni podaci poboljšavaju xG procenu; doprinos ovog rada je u tome što je taj poznati nalaz formalno i transparentno provjeren kroz Leave-One-Tournament-Out validacionu šemu, koja u dostupnoj literaturi nije uobičajeno kombinovana sa modelom na nivou pojedinačnog šuta i StatsBomb 360 atributima.'),

    h2('5.2. Generalizacija kroz turnire'),
    p('Nalaz da Stratified K-Fold i Leave-One-Tournament-Out validacija daju praktično identične rezultate je ohrabrujući u pogledu robusnosti modela, ali zahteva oprez u tumačenju. Formalni Kolmogorov-Smirnov test je potvrdio da je geometrija šuta (udaljenost, ugao) statistički slična kroz sva tri turnira, što je verovatno glavni razlog zašto model generalizuje tako dobro: model se u najvećoj meri oslanja na geometrijske obrasce koji su univerzalni za fudbalsku igru, a ne na specifičnosti pojedinačnog turnira.'),
    p('Sa druge strane, stopa konverzije šuteva u gol značajno se razlikuje između turnira, pri čemu Evropsko prvenstvo 2024 ima primetno nižu stopu. Pošto se ta razlika ne objašnjava razlikom u geometriji šuta, najverovatnije poticanje je iz faktora koje model ne hvata, kao što su individualni kvalitet izvedbe igrača, kvalitet golmana ili jednostavno slučajnost u malom uzorku. Ovo postavlja prirodnu granicu očekivanog performansa modela: deo varijanse u ishodu šuta je, po svojoj prirodi, neobjašnjiv geometrijskim i prostornim atributima.'),

    h2('5.3. Praktična primena'),
    p('Nalazi rada imaju nekoliko mogućih praktičnih primena u fudbalskoj analitici. Trenerski štab i analitičari mogu koristiti razliku između Modela A i Modela B kao indikator koliko je konkretna šansa bila kvalitetnija ili lošija nego što čista geometrija šuta sugeriše, što je korisno za retrospektivnu analizu kvaliteta stvorenih šansi (na primer, da li je tim sistematski stvarao šanse iz situacija sa malo defanzivnog pritiska, ili obrnuto). U skautingu, SHAP interpretacija modela može pomoći u identifikaciji igrača koji konzistentno postižu golove iz situacija sa visokim defanzivnim pritiskom, što ukazuje na veštinu koja nadilazi čistu poziciju na terenu. U evaluaciji golmana, atribut anomalije pozicije golmana, koji meri odstupanje od očekivane pozicije za datu udaljenost šuta, može poslužiti kao osnova za dalju analizu pozicioniranja.'),

    h2('5.4. Ograničenja istraživanja'),
    p('Rad ima nekoliko metodoloških ograničenja koja treba eksplicitno navesti. Prvo, šutevi istog igrača ili tima nisu nezavisne opservacije u strogom statističkom smislu, jer pojedinačni igrači ili timovi mogu sistematski odstupati od proseka po kvalitetu izvedbe. Zbog obima rada, primenjen je standardni model bez eksplicitnog modelovanja ove hijerarhijske strukture (na primer, mešoviti model sa nasumičnim efektima po igraču), što ostaje pravac za buduća istraživanja.'),
    p('Drugo, Leave-One-Tournament-Out validacija je sprovedena sa samo tri turnira, što ograničava statističku snagu procene varijanse generalizacije, i dva od tri turnira (oba izdanja Evropskog prvenstva) strukturno su sličnija jedan drugom nego Svetskom prvenstvu, čime se delimično umanjuje raznovrsnost validacionog skupa.'),
    p('Treće, geometrijska aproksimacija prostornih atributa (na primer, definicija konusa šuta, fizička širina igrača prilikom procene blokiranog ugla) predstavlja zadovoljavajuću, ali svesno pojednostavljenu reprezentaciju stvarne fizičke situacije na terenu, u odnosu na, na primer, komercijalne modele koji koriste potpunu sekvencu događaja koja prethodi šutu, brzinu i putanju lopte, te orijentaciju tela igrača.'),
    p('Četvrto, izotona regresija primenjena za post-hoc kalibraciju ima poznatu karakteristiku da kompresuje ekstremne predviđene vrednosti, posebno kada je broj golova u najvišim binovima predviđenih verovatnoća ograničen, što treba imati u vidu prilikom tumačenja kalibrisanih izlaza modela.'),
    p('Peto, atributi nisu skalirani pre primene L2-regularizovane logističke regresije, što znači da regularizacioni parametar C neravnomerno penalizuje koeficijente atributa različitih skala, na primer minut utakmice u opsegu od 0 do 120 naspram binarnog indikatora 0 ili 1. S obzirom na to da je optimalni C približno 0,85, što predstavlja relativno slabu regularizaciju, i da se interpretacija koeficijenata kroz Odds Ratio temelji na zasebnom fitovanju metodom maksimalne verodostojnosti bez penalizacije, efekat ovog propusta na konačne zaključke procenjuje se kao zanemarljiv, ali se navodi kao metodološka nepreciznost.'),

    h1('Zaključak', true, '6'),
    p('Ovaj rad je testirao da li StatsBomb 360 prostorni podaci o rasporedu igrača na terenu doprinose proceni verovatnoće gola u odnosu na model koji koristi samo klasične atribute samog šuta. Analiza na 3.968 šuteva iz tri velika međunarodna turnira (Svetsko prvenstvo 2022, Evropsko prvenstvo 2020 i Evropsko prvenstvo 2024) pokazala je da model sa StatsBomb 360 atributima konzistentno nadmašuje model bez njih, na svim metrikama diskriminacije i kalibracije, i u standardnoj unakrsnoj validaciji i u validaciji koja simulira primenu na potpuno nov turnir.'),
    p('Otvorenost ugla ka golu, atribut izveden direktno iz StatsBomb 360 podataka, pokazala se kao drugi najuticajniji prediktor u modelu, odmah iza ugla šuta, što je konkretan i merljiv dokaz vrednosti prostornih podataka. Istovremeno, formalna provera distribucijskog pomaka pokazala je da je geometrija šuta statistički slična kroz sva tri turnira, dok se stopa konverzije značajno razlikuje, što sugeriše da razlike u performansu modela između turnira potiču iz faktora finalizacije šanse, ne iz razlika u kvalitetu ili lokaciji stvorenih šansi.'),
    p('Doprinos ovog rada nije u tvrdnji da su prostorni podaci korisni za xG procenu, jer je taj nalaz već prisutan u literaturi i u praksi komercijalnih provajdera, već u formalnoj, transparentnoj i reproducibilnoj proveri tog nalaza kroz Leave-One-Tournament-Out validacionu šemu na nivou pojedinačnog šuta, što predstavlja precizniji i uži, ali metodološki rigorozniji doprinos postojećoj literaturi o fudbalskoj analitici.'),

    h1('Literatura', true, '7'),
    p('Degrenne, O., & Carling, C. (2024). Comparison of goalscoring patterns between the 2018 and 2022 FIFA World Cups. Frontiers in Sports and Active Living, 6, 1394621. https://doi.org/10.3389/fspor.2024.1394621', { noIndent: true }),
    p('Iapteff, L., Le Coz, S., Rioland, M., Houde, T., Carling, C., & Imbach, F. (2025). Toward interpretable expected goals modeling using Bayesian mixed models. Frontiers in Sports and Active Living, 7, 1504362. https://doi.org/10.3389/fspor.2025.1504362', { noIndent: true }),
    p('Singh, S. (2025). Improving expected Goals (xG) models: methods, results, and novel extensions. Journal of High School Science, 9(3), 475-485. https://doi.org/10.64336/001c.144180', { noIndent: true }),
    p('StatsBomb. (2023). StatsBomb open data repozitorijum [skup podataka]. GitHub. https://github.com/statsbomb/open-data', { noIndent: true }),
    p('van der Wurp, H., Groll, A., Kneib, T., Marra, G., & Radice, R. (2020). Generalised joint regression for count data: a penalty extension for competitive settings. Statistics and Computing, 30(5), 1419-1432. https://doi.org/10.1007/s11222-020-09953-7', { noIndent: true }),
  ];
}

module.exports = { buildPart5 };
