const { h1, h2, p, bullet, numbered } = require('./helpers');

function buildPart5() {
  return [
    h1('Diskusija', true, '5'),

    h2('5.1. Doprinos StatsBomb 360 prostornih podataka'),
    p('Centralni nalaz rada je da Model B konzistentno i u svim primenjenim validacionim šemama nadmašuje Model A, i u pogledu diskriminacije i u pogledu kalibracije. Doprinos nije dramatičan u apsolutnom iznosu (na primer, oko 0,02 razlike u ROC AUC), ali je dosledan kroz sve kombinacije algoritma i validacione šeme, što povećava pouzdanost zaključka da je reč o stvarnom, ne slučajnom efektu. Konkretnija i možda informativnija potvrda dolazi iz SHAP analize, gde se otvorenost ugla ka golu, atribut koji ne postoji bez StatsBomb 360 podataka, plasira kao drugi najuticajniji atribut u celom modelu.'),
    p('Ovaj nalaz je u skladu sa postojećom literaturom o doprinosu prostornih podataka xG modelima, uključujući i sopstvenu praksu kompanije StatsBomb. Rad ne tvrdi da je po prvi put otkrio da prostorni podaci poboljšavaju xG procenu; doprinos ovog rada je u tome što je taj poznati nalaz formalno i transparentno provjeren kroz Leave-One-Tournament-Out validacionu šemu, koja u dostupnoj literaturi nije uobičajeno kombinovana sa modelom na nivou pojedinačnog šuta i StatsBomb 360 atributima.'),

    h2('5.2. Generalizacija kroz turnire'),
    p('Nalaz da Stratified K-Fold i Leave-One-Tournament-Out validacija daju praktično identične rezultate je ohrabrujući u pogledu robusnosti modela, ali zahteva oprez u tumačenju. Formalni Kolmogorov-Smirnov test je potvrdio da je geometrija šuta (udaljenost, ugao) statistički slična kroz sva tri turnira, što je verovatno glavni razlog zašto model generalizuje tako dobro: model se u najvećoj meri oslanja na geometrijske obrasce koji su univerzalni za fudbalsku igru, a ne na specifičnosti pojedinačnog turnira.'),
    p('Sa druge strane, stopa konverzije šuteva u gol značajno se razlikuje između turnira, pri čemu Evropsko prvenstvo 2024 ima primetno nižu stopu. Razlika u konverziji nije objašnjena razlikama u marginalnim raspodelama udaljenosti i ugla šuta (KS test); mogući izvori uključuju završnicu igrača, kvalitet golmana, druge neobuhvaćene karakteristike šuta (brzina, visina lopte, kvalitet asistencije) i slučajnu varijaciju u malom uzorku. Ovo postavlja prirodnu granicu očekivanog performansa modela: deo varijanse u ishodu šuta je, po svojoj prirodi, neobjašnjiv geometrijskim i prostornim atributima.'),

    h2('5.3. Praktična primena'),
    p('Nalazi rada imaju nekoliko mogućih praktičnih primena u fudbalskoj analitici. Trenerski štab i analitičari mogu koristiti razliku između Modela A i Modela B kao indikator koliko je konkretna šansa bila kvalitetnija ili lošija nego što čista geometrija šuta sugeriše. U skautingu, SHAP interpretacija modela može pomoći u identifikaciji igrača koji konzistentno postižu golove iz situacija sa visokim defanzivnim pritiskom, što ukazuje na prediktivnu asocijaciju sa veštinom koja nadilazi čistu poziciju na terenu. U evaluaciji golmana, atribut udaljenosti golmana iz freeze-frame podataka može poslužiti kao osnova za dalju analizu pozicioniranja.'),

    h2('5.4. Ograničenja istraživanja'),
    p('Rad ima nekoliko metodoloških ograničenja koja treba eksplicitno navesti. Prvo, šutevi istog igrača ili tima nisu nezavisne opservacije u strogom statističkom smislu, jer pojedinačni igrači ili timovi mogu sistematski odstupati od proseka po kvalitetu izvedbe. Zbog obima rada, primenjen je standardni model bez eksplicitnog modelovanja ove hijerarhijske strukture (na primer, mešoviti model sa nasumičnim efektima po igraču), što ostaje pravac za buduća istraživanja.'),
    p('Drugo, Leave-One-Tournament-Out validacija je sprovedena sa samo tri turnira, što ograničava statističku snagu procene varijanse generalizacije, i dva od tri turnira (oba izdanja Evropskog prvenstva) strukturno su sličnija jedan drugom nego Svetskom prvenstvu, čime se delimično umanjuje raznovrsnost validacionog skupa.'),
    p('Treće, geometrijska aproksimacija prostornih atributa (na primer, definicija konusa šuta, fizička širina igrača prilikom procene blokiranog ugla) predstavlja zadovoljavajuću, ali svesno pojednostavljenu reprezentaciju stvarne fizičke situacije na terenu, u odnosu na, na primer, komercijalne modele koji koriste potpunu sekvencu događaja koja prethodi šutu, brzinu i putanju lopte, te orijentaciju tela igrača.'),
    p('Četvrto, izotona regresija primenjena za post-hoc kalibraciju ima poznatu karakteristiku da kompresuje ekstremne predviđene vrednosti, posebno kada je broj golova u najvišim binovima predviđenih verovatnoća ograničen, što treba imati u vidu prilikom tumačenja kalibrisanih izlaza modela.'),
    p('Peto, atributi nisu skalirani pre primene L2-regularizovane logističke regresije, što znači da regularizacioni parametar C neravnomerno penalizuje koeficijente atributa različitih skala. S obzirom na to da je optimalni C približno 0,85 (relativno slaba regularizacija), efekat ovog propusta procenjuje se kao zanemarljiv, ali se navodi kao metodološka nepreciznost.'),
    p('Šesto, Stratified K-Fold validacija deli šuteve na nivou pojedinačnih opservacija, ne na nivou mečeva. Šutevi iz istog meča mogu završiti u trening i test delu, što može dati blago optimističniju procenu performansa. LOTO validacija adresira ovaj problem na nivou turnira, ali unutar nje K-Fold i dalje deli po šutevima. StratifiedGroupKFold sa meč ID-em kao grupom bi bio stroži pristup.'),
    p('Sedmo, bootstrap analiza je sprovedena na nivou pojedinačnih šuteva (parno resamplovanje), što čuva uparivanje Model A/B predikcija za isti šut, ali ne čuva zavisnost šuteva unutar istog meča. Cluster bootstrap po mečevima bi bio robusniji pristup.'),
    p('Osmo, StatsBomb 360 freeze-frame sadrži samo igrače vidljive kameri u trenutku šuta, ne nužno sve igrače na terenu. Count i density atributi (broj protivnika, pressure_score) mogu biti potcenjeni ako relevantan deo terena nije u vidnom polju kamere. Ovo ograničenje je inherentno izvoru podataka.'),
    p('Deveto, koordinate su u StatsBomb sistemu (0-120 x 0-80), a radijus defanzivnog pritiska i širina gola su izraženi u fizičkim jedinicama (jardi/metri). Konverzija je primenjenja linerano (1 SB jedinica = 105/120 = 0,875m za x-osu), ali ovo treba jasno navesti jer StatsBomb ne objavljuje zvanično mapiranje na fizičke dimenzije terena.'),

    h1('Zaključak', true, '6'),
    p('Ovaj rad je testirao da li StatsBomb 360 prostorni podaci o rasporedu igrača na terenu doprinose proceni verovatnoće gola u odnosu na model koji koristi samo klasične atribute samog šuta. Analiza na 3.968 šuteva iz tri velika međunarodna turnira (Svetsko prvenstvo 2022, Evropsko prvenstvo 2020 i Evropsko prvenstvo 2024) pokazala je da model sa StatsBomb 360 atributima konzistentno nadmašuje model bez njih, na svim metrikama diskriminacije i kalibracije, i u standardnoj unakrsnoj validaciji i u validaciji koja simulira primenu na potpuno nov turnir.'),
    p('Otvorenost ugla ka golu, atribut izveden direktno iz StatsBomb 360 podataka, pokazala se kao drugi najuticajniji prediktor u fitovanom XGBoost modelu, odmah iza ugla šuta. Ovo je nalaz o prediktivnoj asocijaciji, ne o uzročnom efektu: SHAP objašnjava ponašanje konkretnog modela, ali ne dokazuje da promena otvorenosti gola uzrokuje promenu ishoda. Istovremeno, formalna provera distribucijskog pomaka (KS test) pokazala je da su marginalne raspodele udaljenosti i ugla šuta statistički slične kroz sva tri turnira, dok se stopa konverzije značajno razlikuje. Ovo ne dokazuje jednakost ukupnog kvaliteta šansi (mogu se razlikovati zajednička raspodela, tip asistencije, brzina lopte i drugi faktori), ali sugeriše da razlike u performansu modela između turnira ne potiču iz grubih razlika u geometrijskoj distribuciji šuteva.'),
    p('Doprinos ovog rada nije u tvrdnji da su prostorni podaci korisni za xG procenu, jer je taj nalaz već prisutan u literaturi i u praksi komercijalnih provajdera, već u formalnoj, transparentnoj i reproducibilnoj proveri tog nalaza kroz Leave-One-Tournament-Out validacionu šemu na nivou pojedinačnog šuta, što predstavlja precizniji i uži, ali metodološki rigorozniji doprinos postojećoj literaturi o fudbalskoj analitici.'),

    h1('Literatura', true, '7'),
    p('Degrenne, O., & Carling, C. (2024). Comparison of goalscoring patterns between the 2018 and 2022 FIFA World Cups. Frontiers in Sports and Active Living, 6, 1394621. https://doi.org/10.3389/fspor.2024.1394621', { noIndent: true }),
    p('Iapteff, L., Le Coz, S., Rioland, M., Houde, T., Carling, C., & Imbach, F. (2025). Toward interpretable expected goals modeling using Bayesian mixed models. Frontiers in Sports and Active Living, 7, 1504362. https://doi.org/10.3389/fspor.2025.1504362', { noIndent: true }),
    p('Singh, S. (2025). Improving expected Goals (xG) models: methods, results, and novel extensions. Journal of High School Science, 9(3), 475-485. https://doi.org/10.64336/001c.144180', { noIndent: true }),
    p('StatsBomb. (2023). StatsBomb open data repozitorijum [skup podataka]. GitHub. https://github.com/statsbomb/open-data', { noIndent: true }),
    p('van der Wurp, H., Groll, A., Kneib, T., Marra, G., & Radice, R. (2020). Generalised joint regression for count data: a penalty extension for competitive settings. Statistics and Computing, 30(5), 1419-1432. https://doi.org/10.1007/s11222-020-09953-7', { noIndent: true }),
  ];
}

module.exports = { buildPart5 };
