const { h1, h2, p, bullet, numbered } = require('./helpers');

function buildPart5() {
  return [
    h1('Diskusija', true, '5'),

    h2('5.1. Doprinos StatsBomb 360 prostornih podataka'),
    p('Centralni nalaz rada je da Model B konzistentno poboljšava diskriminaciju (ROC AUC, PR AUC) u odnosu na Model A, dok su razlike u kalibrisanom Brier skoru male ali dosledne. Doprinos nije dramatičan u apsolutnom iznosu (oko 0,01 razlike u ROC AUC), ali je dosledan kroz sve kombinacije algoritma i validacione šeme, što povećava pouzdanost zaključka da 360 atributi sadrže dodatnu prediktivnu informaciju. Konkretnija potvrda dolazi iz SHAP analize, gde se udaljenost golmana (goalkeeper_distance_360) plasira kao najuticajniji 360 atribut u modelu, odmah iza ugla šuta.'),
    p('Ovaj nalaz je u skladu sa postojećom literaturom o doprinosu prostornih podataka xG modelima, uključujući i sopstvenu praksu kompanije StatsBomb. Rad ne tvrdi da je po prvi put otkrio da prostorni podaci poboljšavaju xG procenu; doprinos ovog rada je u tome što je taj poznati nalaz formalno i transparentno provjeren kroz Leave-One-Tournament-Out validacionu šemu, koja u dostupnoj literaturi nije uobičajeno kombinovana sa modelom na nivou pojedinačnog šuta i StatsBomb 360 atributima.'),

    h2('5.2. Generalizacija kroz turnire'),
    p('Nalaz da StratifiedGroupKFold po meču i Leave-One-Tournament-Out validacija daju slične rezultate je ohrabrujući u pogledu robusnosti modela. Kolmogorov-Smirnov test nije pronašao dokaz da se marginalne raspodele udaljenosti i ugla šuta razlikuju između turnira, što je kompatibilno sa hipotezom da model koristi geometrijske obrasce koji su relativno univerzalni za fudbalsku igru, mada samo-marginalne raspodele ne isključuju razlike u zajedničkoj distribuciji ili drugim nemerenim faktorima.'),
    p('Sa druge strane, stopa konverzije šuteva u gol značajno se razlikuje između turnira, pri čemu Evropsko prvenstvo 2024 ima primetno nižu stopu. Razlika u konverziji nije objašnjena razlikama u marginalnim raspodelama udaljenosti i ugla šuta (KS test); mogući izvori uključuju završnicu igrača, kvalitet golmana, druge neobuhvaćene karakteristike šuta (brzina, visina lopte, kvalitet asistencije) i slučajnu varijaciju u malom uzorku. Ovo postavlja prirodnu granicu očekivanog performansa modela: deo varijanse u ishodu šuta je, po svojoj prirodi, neobjašnjiv geometrijskim i prostornim atributima.'),

    h2('5.3. Praktična primena'),
    p('Nalazi rada imaju nekoliko mogućih praktičnih primena u fudbalskoj analitici. Trenerski štab i analitičari mogu koristiti razliku između Modela A i Modela B kao indikator koliko je konkretna šansa bila kvalitetnija ili lošija nego što čista geometrija šuta sugeriše. U skautingu, SHAP interpretacija modela može pomoći u identifikaciji igrača koji konzistentno postižu golove iz situacija sa visokim defanzivnim pritiskom, što ukazuje na prediktivnu asocijaciju sa veštinom koja nadilazi čistu poziciju na terenu. U evaluaciji golmana, atribut udaljenosti golmana iz freeze-frame podataka može poslužiti kao osnova za dalju analizu pozicioniranja.'),

    h2('5.4. Ograničenja istraživanja'),
    p('Rad ima nekoliko metodoloških ograničenja koja treba eksplicitno navesti. Prvo, šutevi istog igrača ili tima nisu nezavisne opservacije u strogom statističkom smislu, jer pojedinačni igrači ili timovi mogu sistematski odstupati od proseka po kvalitetu izvedbe. Zbog obima rada, primenjen je standardni model bez eksplicitnog modelovanja ove hijerarhijske strukture (na primer, mešoviti model sa nasumičnim efektima po igraču), što ostaje pravac za buduća istraživanja.'),
    p('Drugo, Leave-One-Tournament-Out validacija je sprovedena sa samo tri turnira, što ograničava statističku snagu procene varijanse generalizacije, i dva od tri turnira (oba izdanja Evropskog prvenstva) strukturno su sličnija jedan drugom nego Svetskom prvenstvu, čime se delimično umanjuje raznovrsnost validacionog skupa.'),
    p('Treće, geometrijska aproksimacija prostornih atributa (na primer, definicija konusa šuta, fizička širina igrača prilikom procene blokiranog ugla) predstavlja zadovoljavajuću, ali svesno pojednostavljenu reprezentaciju stvarne fizičke situacije na terenu, u odnosu na, na primer, komercijalne modele koji koriste potpunu sekvencu događaja koja prethodi šutu, brzinu i putanju lopte, te orijentaciju tela igrača.'),
    p('Četvrto, izotona regresija primenjena za post-hoc kalibraciju ima poznatu karakteristiku da kompresuje ekstremne predviđene vrednosti, posebno kada je broj golova u najvišim binovima predviđenih verovatnoća ograničen, što treba imati u vidu prilikom tumačenja kalibrisanih izlaza modela.'),
    p('Peto, numerički atributi su skalirani primenom StandardScaler-a unutar svakog trening folda (kao deo sklearn Pipeline/ColumnTransformer), čime se obezbeđuje da L2 regularizacija ravnomerno penalizuje koeficijente bez obzira na originalnu skalu atributa.'),
    p('Šesto, formalna statistička neizvesnost razlike Model A/B procenjena je cluster bootstrap metodom po utakmicama (166 klastera, 2.000 iteracija), čime je poštovana zavisnost šuteva unutar iste utakmice. Dobijeni 95% interval poverenja za razliku ROC AUC [-0,033, 0,025] obuhvata nulu, što ukazuje da efekat na nivou pojedinačnog šuta, iako konzistentan po smeru kroz validacione šeme i turnire, nije statistički značajan na alfa=0,05 uz konzervativnu korekciju za klastersku zavisnost.'),
    p('Sedmo, StatsBomb 360 freeze-frame sadrži samo igrače vidljive kameri u trenutku šuta, ne nužno sve igrače na terenu. Count i density atributi (broj protivnika, pressure_score) mogu biti potcenjeni ako relevantan deo terena nije u vidnom polju kamere. Ovo ograničenje je inherentno izvoru podataka. Sensitivity analiza (odeljak 4.7) pokazuje da prednost Modela B ostaje konzistentna pri strožim pragovima minimalne vidljivosti (>=5, >=8 vidljivih protivnika), što delimično ublažava ovaj rizik, iako ne može potpuno isključiti efekat nepotpunog kadra na apsolutnu vrednost pojedinačnih atributa.'),
    p('Osmo, StatsBomb koordinatni sistem (120x80) tretiran je kao yard-ekvivalentan na osnovu toga što standardne yard dimenzije fudbalskog terena numerički odgovaraju koordinatama u StatsBomb dokumentaciji (6, 12 i 18 koordinatnih jedinica za kazneni prostor). StatsBomb formalno ne naziva ove jedinice jardima, ali konzistentnost sa standardnim dimenzijama podržava ovu interpretaciju. Svi geometrijski proračuni sprovedeni su dosledno unutar ovog sistema (c=8 za širinu gola, radijus=10 za pritisak).'),

    h1('Zaključak', true, '6'),
    p('Ovaj rad je testirao da li StatsBomb 360 prostorni podaci o rasporedu igrača na terenu doprinose proceni verovatnoće gola u odnosu na model koji koristi samo klasične atribute samog šuta. Analiza na 3.968 šuteva iz tri velika međunarodna turnira (Svetsko prvenstvo 2022, Evropsko prvenstvo 2020 i Evropsko prvenstvo 2024) pokazala je da model sa StatsBomb 360 atributima konzistentno poboljšava ROC AUC i PR AUC u odnosu na model bez njih, dok su razlike u kalibrisanom Brier skoru male ali dosledne, i u standardnoj unakrsnoj validaciji i u validaciji koja simulira primenu na potpuno nov turnir.'),
    p('Udaljenost golmana iz freeze-frame podataka (goalkeeper_distance_360) pokazala se kao najuticajniji 360 prediktor u fitovanom XGBoost modelu, odmah iza ugla šuta. Otvorenost ugla ka golu (open_angle_ratio_360), iako uključena u Model B, rangira se tek na 14. mestu po SHAP važnosti i nije pokazala samostalan inkrementalni doprinos u ablation analizi; eventualna vrednost u punom modelu može odražavati redundanciju sa drugim prostornim atributima. Ovo je nalaz o prediktivnoj asocijaciji, ne o uzročnom efektu. Istovremeno, nije pronađen dokaz da se marginalne raspodele udaljenosti i ugla šuta razlikuju između turnira (KS test); razlika u konverziji stoga nije objašnjena tim dvema posmatranim geometrijskim karakteristikama, a mogući izvori uključuju završnicu, golmanski učinak i slučajnu varijaciju.'),
    p('Doprinos ovog rada nije u tvrdnji da su prostorni podaci korisni za xG procenu, jer je taj nalaz već prisutan u literaturi i u praksi komercijalnih provajdera, već u formalnoj, transparentnoj i reproducibilnoj proveri tog nalaza kroz Leave-One-Tournament-Out validacionu šemu na nivou pojedinačnog šuta, što predstavlja precizniji i uži, ali metodološki rigorozniji doprinos postojećoj literaturi o fudbalskoj analitici.'),

    h1('Literatura', true, '7'),
    p('Degrenne, O., & Carling, C. (2024). Comparison of goalscoring patterns between the 2018 and 2022 FIFA World Cups. Frontiers in Sports and Active Living, 6, 1394621. https://doi.org/10.3389/fspor.2024.1394621', { noIndent: true }),
    p('Fedek, T. (2026). xG360: Doprinos StatsBomb 360 prostornih podataka u proceni verovatnoce gola [izvorni kod]. GitHub. https://github.com/tfedek/xG360', { noIndent: true }),
    p('Iapteff, L., Le Coz, S., Rioland, M., Houde, T., Carling, C., & Imbach, F. (2025). Toward interpretable expected goals modeling using Bayesian mixed models. Frontiers in Sports and Active Living, 7, 1504362. https://doi.org/10.3389/fspor.2025.1504362', { noIndent: true }),
    p('Singh, S. (2025). Improving expected Goals (xG) models: methods, results, and novel extensions. Journal of High School Science, 9(3), 475-485. https://doi.org/10.64336/001c.144180', { noIndent: true }),
    p('StatsBomb. (2023). StatsBomb open data repozitorijum [skup podataka]. GitHub. https://github.com/statsbomb/open-data', { noIndent: true }),
    p('van der Wurp, H., Groll, A., Kneib, T., Marra, G., & Radice, R. (2020). Generalised joint regression for count data: a penalty extension for competitive settings. Statistics and Computing, 30(5), 1419-1432. https://doi.org/10.1007/s11222-020-09953-7', { noIndent: true }),
  ];
}

module.exports = { buildPart5 };
